import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { X, Plane, Building2, Clock, MapPin } from "lucide-react";

interface ItineraryModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ItineraryModal = ({ isOpen, onClose }: ItineraryModalProps) => {
  const itineraryData = [
    {
      day: 1,
      date: "Sat, Sep 27",
      title: "Kochi to Calicut & Flight to Ahmedabad",
      items: [
        {
          type: "flight",
          title: "Flight Departure",
          time: "8:00 AM - 8:15 AM",
          description: "Ernakulam Junction Railway Station",
          icon: <Plane className="w-4 h-4 text-blue-500" />
        },
        {
          type: "hotel",
          title: "Hotel Check-in",
          time: "Check-in 3:00 PM (2 nights)",
          description: "Biznotel By Pride Motera",
          icon: <Building2 className="w-4 h-4 text-emerald-500" />
        }
      ]
    },
    {
      day: 2,
      date: "Sun, Sep 28",
      title: "Explore Ahmedabad",
      items: [
        {
          type: "activity",
          title: "Sabarmati Ashram Visit",
          time: "9:00 AM - 11:00 AM",
          description: "Historical significance and museum tour",
          icon: <MapPin className="w-4 h-4 text-orange-500" />
        },
        {
          type: "activity",
          title: "Akshardham Temple",
          time: "2:00 PM - 5:00 PM",
          description: "Architecture and cultural experience",
          icon: <MapPin className="w-4 h-4 text-orange-500" />
        }
      ]
    },
    {
      day: 3,
      date: "Mon, Sep 29",
      title: "Travel Day & Departure",
      items: [
        {
          type: "hotel",
          title: "Hotel Check-out",
          time: "11:00 AM",
          description: "Biznotel By Pride Motera",
          icon: <Building2 className="w-4 h-4 text-emerald-500" />
        },
        {
          type: "flight",
          title: "Return Flight",
          time: "6:00 PM - 9:30 PM",
          description: "Ahmedabad to Kochi",
          icon: <Plane className="w-4 h-4 text-blue-500" />
        }
      ]
    }
  ];

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-[350px] max-h-[80vh] p-0 rounded-xl">
        <DialogHeader className="p-6 pb-4">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-xl font-bold">Trip Itinerary</DialogTitle>
            <Button
              variant="ghost"
              size="icon"
              onClick={onClose}
              className="w-8 h-8 rounded-full hover:bg-muted"
            >
              <X className="w-4 h-4" />
            </Button>
          </div>
        </DialogHeader>

        <div className="px-6 pb-6 overflow-y-auto">
          <div className="space-y-6">
            {itineraryData.map((day, index) => (
              <div key={day.day} className="space-y-3">
                {/* Day Header */}
                <div className="flex items-center gap-3 pb-2 border-b border-border">
                  <div className="w-8 h-8 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-sm font-bold">
                    {day.day}
                  </div>
                  <div>
                    <h3 className="font-semibold">{day.title}</h3>
                    <p className="text-sm text-muted-foreground">{day.date}</p>
                  </div>
                </div>

                {/* Day Items */}
                <div className="space-y-3 ml-5">
                  {day.items.map((item, itemIndex) => (
                    <div key={itemIndex} className="flex gap-3 p-3 bg-muted/30 rounded-lg">
                      <div className="mt-0.5">{item.icon}</div>
                      <div className="flex-1">
                        <h4 className="font-medium text-sm">{item.title}</h4>
                        <div className="flex items-center gap-1 mt-1">
                          <Clock className="w-3 h-3 text-muted-foreground" />
                          <p className="text-xs text-muted-foreground">{item.time}</p>
                        </div>
                        <p className="text-xs text-muted-foreground mt-1">{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Footer Info */}
          <div className="mt-6 pt-4 border-t border-border">
            <div className="text-center">
              <p className="text-xs text-muted-foreground">
                Total Duration: 3 days
              </p>
              <p className="text-xs text-muted-foreground">
                Generated by AmiGO AI Assistant
              </p>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};